name: structure_creator
description: A simple command-line application.
version: 1.0.0

environment:
  sdk: '>=2.14.4 <3.0.0'

dependencies:
  dotenv: ^3.0.0
  dart_appwrite: ^3.0.2
  path: ^1.8.1
  loggy: ^2.0.1

dev_dependencies:
  lints: ^1.0.1
