name: ownfactory_flutter
description: Own Factory project mobile application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  appwrite: ^2.1.0
  cupertino_icons: ^1.0.4
  elementary: ^1.0.0

  flutter:
    sdk: flutter

  flutter_loggy: ^2.0.1
  flutter_svg: ^1.0.0
  get_it: ^7.2.0
  injectable: ^1.5.0
  loggy: ^2.0.1
  routemaster: ^0.9.5

dev_dependencies:
  build_runner: ^2.1.7
  elementary_test: ^1.0.1

  flutter_test:
    sdk: flutter

  injectable_generator: ^1.5.2
  surf_lint_rules: ^1.4.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/tab_bar/
