name: ownfactory_flutter
description: Own Factory project mobile application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.10.1 <3.0.0"

dependencies:
  appwrite: ^3.0.1
  cupertino_icons: ^1.0.4
  elementary: ^1.1.0
  firebase_auth: ^3.3.9
  firebase_core: ^1.13.1

  flutter:
    sdk: flutter

  flutter_loggy: ^2.0.1
  flutter_svg: ^1.0.3
  get_it: ^7.2.0
  injectable: ^1.5.3
  loggy: ^2.0.1+1
  routemaster: ^0.9.5

  # todo
  # infinite_scroll_pagination
  # flutter_form_builder

dev_dependencies:
  build_runner: ^2.1.7
  elementary_test: ^1.1.0

  flutter_test:
    sdk: flutter

  injectable_generator: ^1.5.2
  surf_lint_rules: ^1.4.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/tab_bar/
