// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMl4RibVcPnuJi73BRsw3-hVDW0yb6Ojk',
    appId: '1:155083846343:web:43533053d97ca3d9a704e2',
    messagingSenderId: '155083846343',
    projectId: 'ownfactory-bbb8b',
    authDomain: 'ownfactory-bbb8b.firebaseapp.com',
    storageBucket: 'ownfactory-bbb8b.appspot.com',
    measurementId: 'G-NB0MBRDKTR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBag8cm7YxmPCJmkd-eRSH4Pka_qJ2Wndg',
    appId: '1:155083846343:android:b4fd36c25bc03cf0a704e2',
    messagingSenderId: '155083846343',
    projectId: 'ownfactory-bbb8b',
    storageBucket: 'ownfactory-bbb8b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzOdteCMDHnulC3CxGInSfeZI9lh22E4k',
    appId: '1:155083846343:ios:0082d7704ea90b98a704e2',
    messagingSenderId: '155083846343',
    projectId: 'ownfactory-bbb8b',
    storageBucket: 'ownfactory-bbb8b.appspot.com',
    iosClientId: '155083846343-v2qc4phk9v2pn4m3udvfcpm6edku1go0.apps.googleusercontent.com',
    iosBundleId: 'org.ownfactory.ownfactoryFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzOdteCMDHnulC3CxGInSfeZI9lh22E4k',
    appId: '1:155083846343:ios:0082d7704ea90b98a704e2',
    messagingSenderId: '155083846343',
    projectId: 'ownfactory-bbb8b',
    storageBucket: 'ownfactory-bbb8b.appspot.com',
    iosClientId: '155083846343-v2qc4phk9v2pn4m3udvfcpm6edku1go0.apps.googleusercontent.com',
    iosBundleId: 'org.ownfactory.ownfactoryFlutter',
  );
}
