name: migration
description: Migration for Appwrite
version: 1.0.0

environment:
  sdk: '>=2.14.4 <3.0.0'

dependencies:
  collection: ^1.15.0
  dart_appwrite: ^2.0.0
  dotenv: ^3.0.0
  loggy: ^2.0.1
  json_annotation: ^4.4.0

dev_dependencies:
  build_runner: ^2.1.7
  json_serializable: ^6.1.3
  lints: ^1.0.1
  test: ^1.20.1
